export type Lang = "de" | "en";

const translations = {
  de: {
    off: "Aus",
    heat: "Heizen",
    cool: "Kühlen",
    dry: "Trocknen",
    auto: "Automatik",
    fan_only: "Nur Lüfter",
    heat_cool: "Heizen/Kühlen",
    target_temperature: "Zieltemperatur",
    unavailable: "Nicht verfügbar",
    open: "Offen",
    select_preset: "Preset wählen",
    preset_none: "Kein Preset",
    progress_status_running: "{remaining} Min. verbleibend",
    progress_status_running_no_remaining: "Läuft",
    progress_status_preparing: "Erkenne Beladung…",
    progress_status_done: "Fertig! Wäsche ist sauber.",
    progress_status_ready: "Bereit",
    editor_entity: "Entität",
    editor_entity_helper: "Optional leer lassen für einen reinen Aktions-Button (z.B. um nur eine Automatisierung/ein Skript auszulösen), ohne dass ein Entity-Zustand angezeigt wird.",
    editor_content: "Inhalt",
    editor_sensors: "Sensoren",
    editor_entities: "Entitäten",
    editor_progress_status_entity: "Status-Entität",
    editor_progress_percentage_entity: "Fortschritt (%) – Sensor",
    editor_progress_remaining_entity: "Restzeit (Min.) – Sensor",
    editor_appearance: "Erscheinungsbild",
    editor_behavior: "Verhalten",
    editor_name: "Name",
    editor_icon: "Icon",
    editor_show_presets: "Preset-Zeile anzeigen",
    editor_show_sensors: "Sensor-Chips anzeigen",
    editor_temperature_sensor: "Temperatur-Sensor",
    editor_humidity_sensor: "Feuchte-Sensor",
    editor_window_sensor: "Fenster-Sensor",
    editor_battery_sensor: "Batterie-Sensor",
    editor_battery_threshold: "Batterie-Schwellwert",
    editor_glass_background: "Glas-Hintergrund",
    editor_mode_color: "Farbe",
    editor_preset_style: "Preset-Darstellung",
    editor_preset_style_chip: "Eigene Zeile (breiter Chip)",
    editor_preset_style_pill: "Als Button in der Modus-Zeile",
    editor_temperature_chip_placement: "Temperatur-Chip Position",
    editor_temp_placement_info_row: "In der Sensor-Zeile",
    editor_temp_placement_header: "Im Header (oben rechts)",
    editor_hidden_modes: "Ausgeblendete Modi",
    editor_height: "Kartenhöhe (leer = automatisch)",
    editor_interactions: "Interaktionen",
    editor_opacity: "Farbstärke",
    editor_color: "Farbe (eingeschaltet/aktiv)",
    editor_color_helper: "Farbe für Icon/Hintergrund, wenn die Entität eingeschaltet/aktiv ist. HA-Farbname (z.B. red, dark-grey) oder beliebige CSS-Farbe (#hex, rgb(...))",
    editor_inactive_color: "Farbe (ausgeschaltet/inaktiv)",
    editor_inactive_color_helper: "Farbe für Icon/Hintergrund, wenn die Entität ausgeschaltet/inaktiv ist (auch bei aktivierter „Statischer Farbe“). Leer = Standardgrau des Themes.",
    editor_invert_colors: "Farben vertauschen (Ein/Aus-Farbe tauschen)",
    editor_static_color: "Statische Farbe (kein Farbwechsel je nach Zustand, nutzt die Farbe „ausgeschaltet/inaktiv“)",
    editor_unavailable_style: "Anzeige bei „nicht verfügbar“",
    editor_unavailable_style_dimmed: "Abgedunkelt (Standard) — ausgegraut, nicht antippbar",
    editor_unavailable_style_normal: "Normal — wie gewohnt anzeigen, weiterhin antippbar",
    editor_unavailable_style_hidden: "Ausgeblendet — Karte wird nicht angezeigt",
    editor_radius: "Eckenradius (px)",
    editor_show_state: "Status-Text anzeigen",
    editor_state_content: "Inhalt des Status-Texts",
    editor_state_content_state: "Zustand",
    editor_state_content_last_changed: "Zuletzt geändert",
    editor_state_content_last_updated: "Zuletzt aktualisiert",
    editor_show_icon_background: "Icon-Hintergrund anzeigen",
    editor_icon_size: "Feste Icon-Größe (px)",
    editor_icon_size_helper: "Standardmäßig passt sich die Icon-Größe automatisch an die Höhe der Kachel an (kleinere Kacheln = kleineres Icon). Hier einen Wert setzen, damit alle Buttons unabhängig von ihrer Größe das gleiche, feste Icon haben. Leer lassen für automatische Größe.",
    editor_align_icons: "Icons an fester Position ausrichten",
    editor_align_icons_helper: "Standardmäßig rückt der Abstand vom linken Rand zum Icon bei kleineren Kacheln etwas näher zusammen. Aktivieren, damit alle Icons unabhängig von der Kartenhöhe am gleichen Abstand vom linken Rand sitzen (z.B. für saubere Ausrichtung übereinander liegender Karten unterschiedlicher Höhe). Die vertikale Zentrierung bleibt davon unberührt.",
    editor_vertical: "Vertikales Layout (Icon oben)",
    editor_tap_action: "Tap-Aktion",
    editor_icon_tap_action: "Tap-Aktion (Icon)",
    editor_hold_action: "Halten-Aktion",
    editor_icon_hold_action: "Halten-Aktion (Icon)",
    editor_double_tap_action: "Doppeltipp-Aktion",
    editor_icon_double_tap_action: "Doppeltipp-Aktion (Icon)",
    editor_show_slider: "Schieberegler anzeigen (Licht/Rollo/Lüfter/Zahl)",
    editor_radius_preset: "Eckenform",
    editor_radius_square: "Eckig",
    editor_radius_soft: "Leicht rund",
    editor_radius_round: "Rund",
    editor_radius_custom: "Benutzerdefiniert (px)",
    editor_state_colors: "Zustandsfarben",
    editor_state_colors_helper: "Optionale Farb-Overrides für bestimmte Zustände (überschreiben die Farbe „eingeschaltet/aktiv“ oben nur für diesen Zustand). Leer lassen für Standard.",
    editor_state_on: "Farbe bei Zustand „Ein“",
    editor_state_open: "Farbe bei Zustand „Offen“",
    editor_state_locked: "Farbe bei Zustand „Verriegelt“",
    editor_state_home: "Farbe bei Zustand „Zuhause“",
    editor_state_playing: "Farbe bei Zustand „Spielt ab“",
    editor_state_active: "Farbe bei Zustand „Aktiv“",
    editor_state_detected: "Farbe bei Zustand „Erkannt“",
    editor_state_wet: "Farbe bei Zustand „Nass“",
    editor_animations: "Animationen",
    editor_use_corners: "Eigene Ecken (jede Ecke einzeln)",
    editor_corner_top_left: "Oben links",
    editor_corner_top_right: "Oben rechts",
    editor_corner_bottom_right: "Unten rechts",
    editor_corner_bottom_left: "Unten links",
    editor_corners_preset: "Ecken-Voreinstellung (füllt alle vier Ecken)",
    editor_element_colors_helper: "Optionale Farb-Overrides je Element, unabhängig von den Modusfarben unten. Leer lassen, damit das Element weiterhin die Modusfarbe verwendet (Icon/Ein-Aus-Button aktiv = Farbe des aktuellen Modus, inaktiv = Farbe von „Aus“).",
    editor_icon_active_color: "Icon-Farbe (aktiv/eingeschaltet)",
    editor_icon_inactive_color: "Icon-Farbe (inaktiv/ausgeschaltet)",
    editor_power_active_color: "Ein-Aus-Button-Farbe (aktiv/eingeschaltet)",
    editor_power_inactive_color: "Ein-Aus-Button-Farbe (inaktiv/ausgeschaltet)",
    editor_plus_active_color: "Plus-Button-Farbe (aktiv/eingeschaltet)",
    editor_plus_inactive_color: "Plus-Button-Farbe (inaktiv/ausgeschaltet)",
    editor_minus_active_color: "Minus-Button-Farbe (aktiv/eingeschaltet)",
    editor_minus_inactive_color: "Minus-Button-Farbe (inaktiv/ausgeschaltet)",
    editor_climate_icon_tint_opacity: "Icon-Hintergrund-Farbstärke",
    editor_climate_plus_tint_opacity: "Plus-Button-Hintergrund-Farbstärke",
    editor_climate_minus_tint_opacity: "Minus-Button-Hintergrund-Farbstärke",
    editor_plus_opacity: "Plus-Button Farbstärke",
    editor_minus_opacity: "Minus-Button Farbstärke",
    editor_progress_status_text_running: "Statustext (Läuft)",
    editor_progress_status_text_running_helper: "{remaining} wird durch den Wert des Restzeit-Sensors ersetzt.",
    editor_progress_status_text_preparing: "Statustext (Vorbereitung)",
    editor_progress_status_text_done: "Statustext (Fertig)",
    editor_progress_status_text_ready: "Statustext (Bereit)",
    editor_progress_state_mapping: "Status-Zuordnung",
    editor_progress_state_mapping_helper: "Werte des Status-Sensors, die als „Läuft“ / „Vorbereitung“ / „Fertig“ gelten (Groß-/Kleinschreibung wird ignoriert). Kommagetrennt. Alle anderen Werte gelten als „Bereit“.",
    editor_progress_running_states: "Läuft – Statuswerte",
    editor_progress_preparing_states: "Vorbereitung – Statuswerte",
    editor_progress_done_states: "Fertig – Statuswerte",
    editor_progress_animation: "Animation",
    editor_progress_animation_auto: "Automatisch (respektiert Systemeinstellung „Bewegung reduzieren“)",
    editor_progress_animation_on: "Immer an",
    editor_progress_animation_off: "Aus",
    editor_progress_animation_reduced_motion_hint: "Hinweis: Ist in den Systemeinstellungen „Bewegung reduzieren“ aktiviert, wird die Welle unabhängig von dieser Einstellung nicht animiert (Barrierefreiheit).",
    editor_progress_wave_style: "Form bei ausgeschalteter Animation",
    editor_progress_wave_style_wavy: "Wellig (eingefroren)",
    editor_progress_wave_style_flat: "Gerade Linie",
    editor_progress_colors: "Farben",
    editor_progress_colors_helper: "Alle Felder optional. Leer lassen = Theme-Standard.",
    editor_progress_accent_color: "Akzentfarbe (Welle/Prozent/Icon)",
    editor_progress_track_color: "Track-Farbe",
    editor_progress_dot_color: "Endpunkt-Farbe",
    editor_progress_icon_color: "Icon-Farbe",
    editor_progress_icon_background: "Icon-Hintergrundfarbe",
    editor_progress_text_color: "Namensfarbe",
    editor_progress_secondary_text_color: "Statuszeilen-Farbe",
    editor_progress_card_background: "Kartenhintergrund",
    editor_light_transition: "Übergangsdauer (Sek.)",
    editor_light_use_light_color: "Eigene Lichtfarbe der Entität nutzen",
    editor_light_use_light_color_helper: "Wenn aus: Akzentfarbe unten wird immer verwendet, auch wenn die Lampe Farbunterstützung hat.",
    editor_light_accent_color: "Akzentfarbe",
    editor_light_track_color: "Schienenfarbe (ungefüllter Teil)",
    editor_light_handle_color: "Griff-Farbe",
    editor_light_wave_style: "Wellen-Stil",
    editor_light_wave_style_wavy: "Wellig",
    editor_light_wave_style_flat: "Flach",
    editor_light_color_temp_style: "Farbtemperatur-Steuerung",
    editor_light_color_temp_style_presets: "Drei Voreinstellungen",
    editor_light_color_temp_style_slider: "Stufenloser Regler",
    editor_light_color_temp_warm: "Warm (K)",
    editor_light_color_temp_neutral: "Neutral (K)",
    editor_light_color_temp_cold: "Kalt (K)",
    editor_light_show_color_wheel: "Farbrad anzeigen",
    editor_light_color_palette: "Farbpalette (Hex, kommagetrennt)",
    editor_light_scenes_helper: "Jede Zeile ist entweder eine scene-Entität ODER ein eigener Service-Aufruf.",
    editor_light_scene_entity: "Szenen-Entität",
    editor_light_scene_service: "Service (z.B. light.turn_on)",
    editor_light_scene_service_data: "Service-Daten (YAML)",
    editor_light_add_scene: "Szene hinzufügen",
    editor_light_show_members: "Gruppenmitglieder auflisten",
    editor_light_show_members_helper: "Nur sichtbar, wenn die Entität eine Lichtgruppe ist (hat ein entity_id-Attribut mit Mitgliedern).",
    editor_scenes: "Szenen",
    editor_progress_state_colors: "Akzentfarbe je Status",
    editor_progress_state_colors_helper: "Überschreibt die Akzentfarbe oben nur für diesen Status (z.B. Grün bei „Fertig“). Leer lassen für Standard.",
    editor_progress_state_running: "Akzentfarbe bei „Läuft“",
    editor_progress_state_preparing: "Akzentfarbe bei „Vorbereitung“",
    editor_progress_state_done: "Akzentfarbe bei „Fertig“",
    editor_progress_hide_when_ready: "Karte komplett ausblenden, wenn „Bereit“",
    editor_progress_hide_when_ready_helper: "Standardmäßig aus — im Zustand „Bereit“ verschwindet nur der Fortschrittsbalken, die Karte bleibt mit Icon/Name/Status sichtbar.",
    energy_subtitle_days: "Letzte {days} Tage",
    energy_subtitle_hours: "Heute · letzte {hours} Stunden",
    energy_subtitle_months: "Pro Monat · {months} Monate",
    energy_month_suffix: "im {month}",
    energy_month_no_statistics: "Für diese Entität wurden keine Monatsstatistiken gefunden. Prüfbar unter Entwicklerwerkzeuge → Statistik.",
    energy_month_chip_less: "{value} % unter {month}",
    energy_month_chip_more: "{value} % über {month}",
    energy_month_chip_average: "Ø {value} {unit}",
    energy_today_suffix: "heute",
    energy_hour_suffix: "diese Std.",
    energy_weekday_today: "Heute",
    energy_hour_now: "Jetzt",
    energy_subtitle_solar: "Heute · Tagesverlauf",
    energy_solar_default_name: "Solarerzeugung",
    energy_solar_expected: "von {value} {unit} erwartet",
    energy_solar_chip_more: "{value} % über gestern",
    energy_solar_chip_less: "{value} % unter gestern",
    energy_legend_generated: "Erzeugt",
    energy_legend_forecast: "Prognose",
    gauge_subtitle_today: "Heute",
    gauge_no_data: "Keine Daten heute",
    gauge_no_energy_dashboard: "Kein Energie-Dashboard konfiguriert",
    gauge_net_grid: "Netto vom Netz bezogen",
    gauge_net_feed_in: "Netto eingespeist",
    gauge_label_a: "Netzbezug",
    gauge_label_b: "Einspeisung",
    counter_subtitle_default: "Gesamtstand",
    counter_ticker_today: "heute",
    editor_energy_mode: "Kartentyp",
    editor_energy_mode_consumption: "Verbrauch/Erzeugung (Balken pro Tag/Stunde)",
    editor_energy_mode_solar: "Solar-Tagesverlauf mit Prognose",
    editor_energy_source: "Datenquelle",
    editor_energy_source_energy: "Energie-Dashboard (alle Solar-Quellen, Standard)",
    editor_energy_source_entity: "Eigener Sensor",
    editor_energy_entity: "Energie-Sensor",
    editor_energy_statistic_type: "Statistik-Typ",
    editor_energy_statistic_type_state: "Tagesendwert (täglich zurücksetzender Zähler) — Standard",
    editor_energy_statistic_type_change: "Änderung (fortlaufender Gesamtzähler)",
    editor_energy_days: "Anzahl Tage",
    editor_energy_period: "Zeitraum",
    editor_energy_period_day: "Tage",
    editor_energy_period_hour: "Stunden",
    editor_energy_period_month: "Monate",
    editor_energy_hours: "Anzahl Stunden",
    editor_energy_months: "Anzahl Monate",
    editor_energy_forecast_entity: "Eigener Prognose-Sensor (optional)",
    editor_energy_full_day: "Immer 0–24 Uhr anzeigen (statt auf Erzeugung/Prognose zu trimmen)",
    editor_energy_show_values: "Werte über den Balken anzeigen",
    editor_energy_show_legend: "Legende anzeigen (Erzeugt/Prognose)",
    editor_energy_show_projection: "Hochrechnung für laufenden Monat anzeigen",
    editor_energy_show_average: "Durchschnittslinie anzeigen",
    editor_energy_show_comparison: "Vergleichs-Chips anzeigen",
    editor_energy_higher_is_better: "Höherer Wert ist besser (z.B. Erzeugung statt Verbrauch)",
    editor_energy_comparison_better_color: "Farbe \"besser\" (Vergleichs-Chip)",
    editor_energy_comparison_worse_color: "Farbe \"schlechter\" (Vergleichs-Chip)",
    editor_energy_comparison_tint_opacity: "Farbstärke (Vergleichs-Chip)",
    editor_energy_subtitle: "Untertitel (leer = automatisch)",
    editor_energy_unit: "Einheit (überschreibt die der Entität, z.B. „L“)",
    editor_energy_accent_color: "Akzentfarbe (heutiger Balken)",
    editor_energy_bar_tint_color: "Balkenfarbe vergangene Tage (leer = automatisch aus Akzentfarbe)",
    editor_energy_fallback_hint: "Für diese Entität wurden keine Langzeitstatistiken gefunden — es wird auf die History-API zurückgegriffen (weniger genau, aggregiert Tageswerte per Maximum). Prüfbar unter Entwicklerwerkzeuge → Statistik.",
    editor_gauge_source: "Datenquelle",
    editor_gauge_source_energy: "Energie-Dashboard (Standard)",
    editor_gauge_source_entities: "Zwei eigene Sensoren",
    editor_gauge_value_a_entity: "Sensor A (Bezug)",
    editor_gauge_value_b_entity: "Sensor B (Einspeisung)",
    editor_gauge_label_positive: "Text bei positivem Netto (Bezug)",
    editor_gauge_label_negative: "Text bei negativem Netto (Einspeisung)",
    editor_gauge_label_a: "Legenden-Label A",
    editor_gauge_label_b: "Legenden-Label B",
    editor_gauge_segment_a_color: "Segmentfarbe A",
    editor_gauge_segment_b_color: "Segmentfarbe B",
    editor_gauge_track_color: "Track-Farbe (keine Daten)",
    editor_counter_power_entity: "Leistungs-Sensor (Chip im Header)",
    editor_counter_daily_entity: "Tages-Sensor (für Ticker-Zeile)",
    editor_counter_decimals: "Nachkommastellen",
    editor_counter_digits_mode: "Vorkommastellen",
    editor_counter_digits_auto: "Automatisch (wächst mit dem Wert, min. 5)",
    editor_counter_digits_fixed: "Feste Anzahl",
    editor_counter_digits: "Anzahl Vorkommastellen",
    editor_counter_show_ticker: "Ticker-Zeile anzeigen (\"+X heute\")",
    editor_counter_accent_color: "Akzentfarbe (Nachkommastellen)",
    editor_counter_cell_background: "Zellen-Hintergrund (Vorkommastellen)",
    editor_counter_power_chip_color: "Power-Chip Farbe (Standard)",
    editor_counter_power_thresholds: "Farbwechsel ab Schwellwert (Format: \"2000:orange, 3500:red\")",
    editor_counter_calibration: "Kalibrierung",
    editor_counter_calibration_hint: "Setzt den Zählerstand einmalig auf einen neuen Wert, z. B. um ihn an einen analogen Zähler anzugleichen. Die Statistik-Historie bleibt dabei unangetastet.",
    editor_counter_calibration_current: "Aktueller Wert",
    editor_counter_calibration_new_value: "Neuer Wert",
    editor_counter_calibration_button: "Jetzt kalibrieren",
    editor_counter_calibration_success: "Kalibriert.",
    editor_counter_calibration_error: "Kalibrierung fehlgeschlagen.",
    power_list_default_name: "Steckdosen",
    power_list_subtitle: "{active} von {total} aktiv",
    power_list_total_suffix: "W gesamt",
    power_list_empty: "Aktuell verbraucht nichts Strom",
    power_list_show_idle: "inaktive Geräte anzeigen",
    power_list_hide_idle: "inaktive Geräte ausblenden",
    editor_power_list_entities: "Sensoren",
    editor_power_list_entities_helper: "Leistungssensoren (W) in Anzeigereihenfolge. Für Name-/Icon-/Typ-Overrides pro Eintrag direkt im YAML-Editor der Karte feinjustieren.",
    editor_power_list_auto_discover: "Automatisch erkennen (alle Sensoren mit device_class „power“)",
    editor_power_list_include_area: "Nur diese Bereiche (leer = alle)",
    editor_power_list_include_label: "Nur diese Labels (leer = alle)",
    editor_power_list_exclude_entities: "Ausgeschlossene Sensoren",
    editor_power_list_threshold: "Schwellwert „aktiv“ (W)",
    editor_power_list_sort: "Sortierung",
    editor_power_list_sort_power_desc: "Leistung absteigend (Standard)",
    editor_power_list_sort_power_asc: "Leistung aufsteigend",
    editor_power_list_sort_name: "Name",
    editor_power_list_sort_config: "Reihenfolge wie konfiguriert",
    editor_power_list_max_visible: "Max. sichtbare Zeilen (0 = alle aktiven)",
    editor_power_list_show_idle_toggle: "Aufklappbereich für inaktive Geräte anzeigen",
    editor_power_list_subtitle: "Untertitel (leer = automatisch)",
    editor_power_list_accent_color: "Akzentfarbe (Verbraucher)",
    editor_power_list_producer_color: "Erzeugerfarbe",
    editor_power_list_bar_tint_color: "Anteilsbalken-Farbe (leer = automatisch aus Akzentfarbe)",
    power_summary_export: "Einspeisung ins Netz",
    power_summary_import: "Bezug aus dem Netz",
    power_summary_neutral: "Ausgeglichen",
    power_summary_unavailable: "Nicht verfügbar",
    power_summary_self_use: "Eigenverbrauch",
    power_summary_grid_share: "Netzbezug",
    power_summary_surplus: "Überschuss",
    editor_summary_grid_entity: "Netz-Sensor (W)",
    editor_summary_grid_sign: "Vorzeichen-Konvention",
    editor_summary_grid_sign_negative: "Negativ = Einspeisung (Standard)",
    editor_summary_grid_sign_positive: "Positiv = Einspeisung",
    editor_summary_consumption_entity: "Verbrauchs-Sensor (W, optional)",
    editor_summary_solar_entity: "Solar-Sensor(en) (W, optional)",
    editor_summary_label_export: "Label bei Einspeisung",
    editor_summary_label_import: "Label bei Bezug",
    editor_summary_show_self_sufficiency: "Autarkie-Chip anzeigen",
    editor_summary_show_split_bar: "Anteilsbalken anzeigen",
    editor_summary_zero_threshold: "Schwellwert „ausgeglichen“ (W)",
    editor_summary_kw_threshold: "Schwellwert für kW-Anzeige (W)",
    editor_summary_metrics: "Kennzahl-Felder",
    editor_summary_metrics_helper: "Eine Zeile pro Feld: entity | Name (optional) | Icon (optional) | Typ (consumer/producer, optional)",
    editor_summary_export_color: "Farbe „Einspeisung“",
    editor_summary_import_color: "Farbe „Bezug“",
    editor_summary_producer_color: "Erzeugerfarbe",
    editor_summary_flow_tint_opacity: "Fluss-Farbstärke",
    editor_summary_accent_color: "Akzentfarbe (Autarkie-Chip)",
    top_consumers_default_name: "Top-Verbraucher",
    top_consumers_period_today: "Heute",
    top_consumers_period_yesterday: "Gestern",
    top_consumers_period_week: "Letzte 7 Tage",
    top_consumers_period_month: "Diesen Monat",
    top_consumers_device_count: "{n} Geräte",
    top_consumers_total_suffix: "kWh gesamt",
    top_consumers_of_total: "vom Gesamtverbrauch",
    top_consumers_more_devices: "{n} weitere Geräte",
    top_consumers_empty: "Noch keine Verbrauchsdaten für {period}",
    top_consumers_no_device_section: "Für dieses Energie-Dashboard ist keine Geräte-Sektion konfiguriert.",
    top_consumers_open_energy_settings: "Energie-Dashboard öffnen",
    editor_top_consumers_source_header: "Datenquelle",
    editor_top_consumers_source: "Quelle",
    editor_top_consumers_source_energy: "Energie-Dashboard (Geräte-Sektion, Standard)",
    editor_top_consumers_source_entities: "Eigene Sensor-Liste",
    editor_top_consumers_entities: "Energie-Sensoren (kWh)",
    editor_top_consumers_period: "Zeitraum",
    editor_top_consumers_period_today: "Heute",
    editor_top_consumers_period_yesterday: "Gestern",
    editor_top_consumers_period_week: "Letzte 7 Tage",
    editor_top_consumers_period_month: "Diesen Monat",
    editor_top_consumers_top_count: "Anzahl volle Zeilen",
    editor_top_consumers_rest_mode: "Rest-Verhalten",
    editor_top_consumers_rest_collapse: "Sammelzeile, aufklappbar (Standard)",
    editor_top_consumers_rest_hide: "Ausblenden",
    editor_top_consumers_rest_show_all: "Alle als volle Zeilen zeigen",
    editor_top_consumers_name_strip_header: "Namensbereinigung",
    editor_top_consumers_name_strip_helper: "Regex-/Text-Muster, die aus Entity-Namen entfernt werden (z.B. „^Steckdose \\d+ - “). Pro Entity über einen eigenen Namen überschreibbar.",
    editor_top_consumers_name_strip: "Muster",
    editor_top_consumers_accent_color: "Akzentfarbe (Gesamtsumme)",
    editor_top_consumers_palette: "Gerätefarben-Palette (zyklisch zugewiesen)",
    cost_default_name: "Kosten",
    cost_no_price_configured: "Kein Preis konfiguriert.",
    cost_subtitle_day: "Kosten heute",
    cost_subtitle_day_date: "Kosten am {date}",
    cost_nav_period_label: "Zeitraum",
    cost_subtitle_month: "Kosten im {month}",
    cost_subtitle_year: "Kosten {year}",
    cost_credit_label: "Gutschrift",
    cost_forecast_hint: "Prognose ab morgen",
    cost_chip_more: "{value} % mehr als Vorperiode",
    cost_chip_less: "{value} % weniger als Vorperiode",
    cost_budget_percent: "{value} % vom Budget",
    cost_avg_per_day: "Ø {value} / Tag",
    cost_tariff_label: "Arbeitspreis",
    editor_cost_price_section: "Preis",
    editor_cost_price_source: "Preisquelle",
    editor_cost_price_source_energy_dashboard: "Energie-Dashboard (Standard)",
    editor_cost_price_source_input_number: "input_number-Helfer",
    editor_cost_price_source_fixed: "Fester Preis",
    editor_cost_price_entity: "Preis-Helfer (input_number)",
    editor_cost_price: "Preis pro kWh",
    editor_cost_price_unit: "Preis-Einheit",
    editor_cost_price_unit_eur: "€/kWh",
    editor_cost_price_unit_ct: "ct/kWh",
    editor_cost_price_unit_custom: "Benutzerdefiniert",
    editor_cost_price_unit_label: "Einheit (Anzeige, z.B. €/m³)",
    editor_cost_price_quantity_factor: "Mengen-Umrechnungsfaktor",
    editor_cost_base_fee: "Grundgebühr (€/Monat)",
    editor_cost_base_fee_helper: "Wird bei Zeitraum „Monat“ anteilig pro Tag zur Kostensumme addiert.",
    editor_cost_currency: "Währung (ISO-Code, z.B. EUR)",
    editor_cost_period: "Zeitraum",
    editor_cost_period_day: "Heute",
    editor_cost_period_month: "Monat",
    editor_cost_period_year: "Jahr",
    editor_cost_entity: "Energie-Sensor (kWh)",
    editor_cost_show_projection: "Prognose-Chip anzeigen",
    editor_cost_show_comparison: "Vergleichs-Chip anzeigen",
    editor_cost_budget: "Budget (optional)",
    editor_top_consumers_unit_mode: "Anzeige",
    editor_top_consumers_unit_mode_energy: "Energie (kWh)",
    editor_top_consumers_unit_mode_cost: "Kosten",
    top_consumers_of_total_cost: "der Kosten",
    light_default_name: "Licht",
    light_brightness_label: "Helligkeit",
    light_color_temp_label: "Farbtemperatur",
    light_color_wheel_label: "Farbe",
    light_scene_unnamed: "Szene",
    battery_default_name: "Batterien",
    battery_subtitle_attention: "{n} brauchen Aufmerksamkeit",
    battery_subtitle_ok: "Alles in Ordnung",
    battery_empty: "Keine Batterie-Entities gefunden. Karte erkennt Sensoren mit device_class „battery“ automatisch (auto_discover) oder nimm sie manuell in „entities“ auf.",
    battery_value_unavailable: "—",
    battery_expand: "{n} weitere anzeigen",
    battery_collapse: "Einklappen",
    editor_battery_auto_discover: "Automatisch erkennen",
    editor_battery_auto_discover_helper: "Erkennt alle Sensoren mit device_class „battery“ automatisch. Einträge unten überschreiben dann nur Name/Icon einzelner Geräte, statt die Liste zu ersetzen.",
    editor_battery_convert_to_manual: "Aktuelle Liste übernehmen & manuell verwalten",
    editor_battery_convert_to_manual_helper: "Übernimmt alle {n} aktuell automatisch erkannten Geräte als feste Liste — danach einzeln mit „×“ entfernen statt jedes gewünschte Gerät neu hinzuzufügen.",
    editor_battery_include_area: "Bereich einschränken",
    editor_battery_include_label: "Label einschränken",
    editor_battery_exclude_entities: "Ausgeschlossene Entitäten",
    editor_battery_overrides_helper: "Ohne „Automatisch erkennen“ ist dies die vollständige Geräteliste. Mit „Automatisch erkennen“ überschreibt ein Eintrag nur Name/Icon des jeweiligen Geräts.",
    editor_battery_override_entity: "Entität",
    editor_battery_add_override: "Gerät hinzufügen",
    editor_battery_thresholds: "Schwellwerte",
    editor_battery_thresholds_helper: "Ladestand in %, unterhalb dessen die jeweilige Stufe gilt.",
    editor_battery_threshold_critical: "Kritisch unter",
    editor_battery_threshold_low: "Niedrig unter",
    editor_battery_threshold_medium: "Mittel unter",
    editor_battery_name_strip: "Namens-Suffixe entfernen",
    editor_battery_max_visible: "Max. sichtbare Geräte (0 = alle)",
    editor_battery_show_healthy_toggle: "Aufklapp-Button für weitere Geräte anzeigen",
    editor_battery_critical_color: "Farbe „Kritisch“",
    editor_battery_low_color: "Farbe „Niedrig“",
    editor_battery_medium_color: "Farbe „Mittel“",
    editor_battery_ok_color: "Farbe „In Ordnung“",
    editor_battery_unavailable_color: "Farbe „Nicht verfügbar“",
    editor_battery_stage_tint_opacity: "Status-Farbstärke",
    a11y_more_info: "Mehr Informationen zu {name}",
    a11y_toggle_expand: "Weitere anzeigen",
    a11y_toggle_collapse: "Einklappen",
    flow_default_name: "Energieverteilung",
    flow_subtitle_today: "Heute",
    flow_node_pv: "PV",
    flow_node_grid: "Netz",
    flow_node_home: "Haus",
    flow_node_battery: "Batterie",
    flow_self_sufficiency: "Autarkie heute",
    editor_flow_source: "Datenquelle",
    editor_flow_source_energy: "Energie-Dashboard (Standard)",
    editor_flow_source_entities: "Eigene Sensoren",
    editor_flow_solar_entity: "Solar-Sensor (heute, kWh)",
    editor_flow_grid_import_entity: "Netzbezug-Sensor (heute, kWh)",
    editor_flow_grid_export_entity: "Einspeisung-Sensor (heute, kWh)",
    editor_flow_battery_entity: "Batterie-Entladung-Sensor (heute, kWh, optional)",
    editor_flow_show_self_sufficiency: "Autarkie-Anzeige zeigen",
    editor_flow_pv_color: "Solar-Farbe",
    editor_flow_grid_color: "Netz-Farbe",
    editor_flow_home_color: "Haus-Farbe",
    editor_flow_self_sufficiency_color: "Autarkie-Farbe",
    editor_flow_node_tint_opacity: "Knoten-Farbstärke",
    editor_flow_speed: "Fließgeschwindigkeit",
    editor_flow_speed_slow: "Langsam",
    editor_flow_speed_normal: "Normal",
    editor_flow_speed_fast: "Schnell",
    weather_now: "Jetzt",
    weather_today: "Heute",
    weather_no_hourly_forecast: "Diese Wetter-Entität liefert keine Stundenvorhersage.",
    weather_last_known: "Letzter bekannter Stand",
    weather_days_expand: "{n} weitere anzeigen",
    weather_days_collapse: "Einklappen",
    editor_weather_hours: "Anzahl Stunden",
    editor_weather_days: "Anzahl Tage",
    editor_weather_days_helper:
      "0 = Tagesvorhersage ausblenden. Wie viele Tage tatsächlich angezeigt werden, hängt von der Wetter-Integration ab (Met.no liefert z.B. maximal 6 Tage) — ab 4 Tagen ist die Liste standardmäßig aufklappbar.",
    editor_weather_show_days_toggle: "Aufklapp-Button für weitere Tage anzeigen",
    editor_weather_no_entity_hint:
      "Keine Wetter-Entität gefunden. Ohne eigene Wetterstation reicht die kostenlose, in Home Assistant eingebaute Met.no-Integration (kein API-Key nötig): Einstellungen → Geräte & Dienste → Integration hinzufügen → „Met.no“ suchen. Sie nutzt automatisch die Koordinaten deiner Home-Zone.",
    editor_weather_chip_no_data: "keine Daten",
    editor_weather_chips_helper:
      "Nicht jede Wetter-Integration liefert alle Werte — Met.no z.B. hat keine „Gefühlt“- oder „Sichtweite“-Daten. Chips ohne Daten bleiben ausgeblendet, auch wenn sie ausgewählt sind.",
    editor_weather_chips: "Chips",
    editor_weather_show_sun: "Sonnenauf-/-untergang anzeigen",
    editor_weather_accent_color: "Temperaturkurve",
    editor_weather_precipitation_color: "Niederschlag",
    editor_weather_gradient_color: "Verlaufsfüllung",
    chip_apparent_temperature: "Gefühlt",
    chip_wind_speed: "Wind",
    chip_humidity: "Luftfeuchte",
    chip_pressure: "Luftdruck",
    chip_uv_index: "UV-Index",
    chip_visibility: "Sichtweite",
    presence_default_name: "Zuhause",
    presence_subtitle: "{home} von {total} zu Hause",
    presence_nobody_home: "Niemand da",
    presence_empty: "Keine Personen konfiguriert.",
    presence_home: "Zuhause",
    presence_not_home: "Abwesend",
    since_minutes: "seit {n} Min.",
    since_hours: "seit {n} Std.",
    since_days: "seit {n} Tg.",
    editor_presence_auto_discover: "Alle person-Entitäten automatisch erkennen",
    editor_presence_show_distance: "Entfernung anzeigen",
    editor_presence_show_since: "Abwesenheitsdauer anzeigen",
    editor_presence_show_map: "Kartenvorschau anzeigen",
    editor_presence_show_map_helper: "Bettet Home Assistants Karten-Karte ein — kann bei vielen Personen/Updates spürbar mehr Ressourcen verbrauchen.",
    editor_presence_sort: "Sortierung",
    editor_presence_sort_home_first: "Zuhause zuerst",
    editor_presence_sort_name: "Alphabetisch",
    editor_presence_home_color: "Zuhause",
    editor_presence_not_home_color: "Abwesend",
    editor_presence_zone_color: "Zone (Standard)",
    editor_presence_unknown_color: "Unbekannt",
    media_off: "Aus",
    media_idle: "Bereit",
    media_volume_label: "Lautstärke",
    editor_media_show_source_select: "Quellenauswahl anzeigen",
    editor_media_show_shuffle_repeat: "Shuffle/Repeat anzeigen",
    editor_media_use_artwork_color: "Akzentfarbe aus Cover",
    editor_media_accent_color: "Akzentfarbe (Fallback)",
    climate_overview_default_name: "Raumklima",
    climate_overview_subtitle: "{n} Räume · Ø {temp}",
    climate_overview_subtitle_one: "1 Raum · Ø {temp}",
    climate_overview_empty: "Keine Temperatursensoren gefunden.",
    climate_overview_unavailable: "—",
    climate_overview_compare: "Im Vergleich",
    climate_overview_mold_risk: "Schimmelrisiko",
    aquarium_default_name: "Aquarium",
    aquarium_water_label: "Wasser",
    aquarium_state_on: "An",
    aquarium_action_start: "Start",
    aquarium_cleaned_today: "Heute",
    aquarium_cleaned_days_ago: "vor {n} T.",
    aquarium_phase_day: "Tagphase",
    aquarium_phase_night: "Nachtruhe",
    aquarium_phase_light_from: "Licht ab {time}",
    aquarium_phase_remaining_hours: "noch {h} Std.",
    aquarium_phase_remaining_minutes: "noch {m} Min.",
    aquarium_live: "LIVE",
    aquarium_camera_no_image: "Kein Bild",
    aquarium_camera_toggle: "Kamerabild ein-/ausklappen",
    aquarium_chip_temp_above: "{x} K über Soll",
    aquarium_chip_temp_below: "{x} K unter Soll",
    aquarium_chip_heater_no_power: "Heizer an · 0 W",
    aquarium_chip_cleaning_due: "Säubern fällig",
    aquarium_chip_cleaned_days_ago: "Gesäubert vor {n} T.",
    aquarium_chip_cleaned_today: "Heute gesäubert",
    aquarium_chip_water_level_low: "Wasserstand niedrig",
    editor_aquarium_general: "Allgemein",
    editor_aquarium_accent_color: "Akzentfarbe",
    editor_aquarium_tile_tint_opacity: "Kachel-Farbstärke",
    editor_aquarium_water: "Wasserwerte",
    editor_aquarium_water_temperature_entity: "Wassertemperatur-Sensor",
    editor_aquarium_target_min: "Sollbereich Min",
    editor_aquarium_target_max: "Sollbereich Max",
    editor_aquarium_ph_entity: "pH-Sensor",
    editor_aquarium_tds_entity: "TDS-Sensor",
    editor_aquarium_water_level_entity: "Wasserstand-Sensor (Problem-Meldung, binary_sensor)",
    editor_aquarium_power_entity: "Gesamtleistung-Sensor",
    editor_aquarium_devices: "Geräte",
    editor_aquarium_light_day: "Tageslicht",
    editor_aquarium_light_night: "Nachtlicht",
    editor_aquarium_pump: "Pumpe",
    editor_aquarium_heater: "Heizer",
    editor_aquarium_heater_power_entity: "Heizer-Leistungssensor",
    editor_aquarium_co2: "CO₂",
    editor_aquarium_extra_devices: "Weitere Geräte",
    editor_aquarium_add_device: "Gerät hinzufügen",
    editor_aquarium_camera: "Kamera",
    editor_aquarium_camera_entity: "Kamera-Entität",
    editor_aquarium_camera_style: "Darstellung",
    editor_aquarium_camera_style_none: "Keine",
    editor_aquarium_camera_style_thumbnail: "Thumbnail",
    editor_aquarium_camera_style_banner: "Banner",
    editor_aquarium_camera_style_live: "Live-Stream",
    editor_aquarium_camera_refresh: "Bild-Aktualisierung (Sek., 0 = aus)",
    editor_aquarium_camera_live_on_tap: "Tap öffnet Live-Stream",
    editor_aquarium_schedule: "Beleuchtungsplan",
    editor_aquarium_schedule_entity: "Zeitplan-Helfer (schedule-Domain)",
    editor_aquarium_schedule_helper: "Ein schedule-Helfer überschreibt die manuelle Phasenliste unten, falls beides gesetzt ist.",
    editor_aquarium_show_schedule: "Tagesbogen anzeigen",
    editor_aquarium_phase_device: "Phase",
    editor_aquarium_phase_day: "Tag",
    editor_aquarium_phase_night: "Nacht",
    editor_aquarium_phase_start: "Start",
    editor_aquarium_phase_end: "Ende",
    editor_aquarium_add_phase: "Phase hinzufügen",
    editor_aquarium_maintenance: "Wartung",
    editor_aquarium_cleaning_entity: "Reinigungs-Zeitstempel (input_datetime)",
    editor_aquarium_cleaning_interval: "Reinigungsintervall (Tage)",
    editor_climate_overview_auto_discover: "Automatisch erkennen",
    editor_climate_overview_auto_discover_helper: "Erkennt alle Sensoren mit device_class „temperature“ bzw. „humidity“ automatisch, gruppiert nach Bereich/Gerät.",
    editor_climate_overview_include_area: "Bereich einschränken",
    editor_climate_overview_exclude_entities: "Ausgeschlossene Entitäten",
    editor_climate_overview_rooms_helper: "Manuelle Raumliste (überschreibt Auto-Discovery, wenn nicht leer).",
    editor_climate_overview_add_room: "Raum hinzufügen",
    editor_climate_overview_room_name: "Name",
    editor_climate_overview_room_icon: "Icon",
    editor_climate_overview_room_temp_entity: "Temperatur-Sensor",
    editor_climate_overview_room_humidity_entity: "Feuchte-Sensor",
    editor_climate_overview_room_color: "Eigene Farbe (überschreibt Temperaturfarbe)",
    editor_climate_overview_sort: "Sortierung",
    editor_climate_overview_sort_area: "Bereich (Standard)",
    editor_climate_overview_sort_temp_desc: "Temperatur absteigend",
    editor_climate_overview_sort_temp_asc: "Temperatur aufsteigend",
    editor_climate_overview_sort_name: "Alphabetisch",
    editor_climate_overview_show_scale: "Vergleichsskala anzeigen",
    editor_climate_overview_show_outlier_chip: "Hinweis-Chip anzeigen",
    editor_climate_overview_show_trend: "Trendpfeil anzeigen",
    editor_climate_overview_show_mold_warning: "Schimmel-Warnung anzeigen",
    editor_climate_overview_name_strip: "Namens-Suffixe entfernen",
    editor_climate_overview_thresholds_helper: "Grenzen zwischen den Temperaturfarbstufen (kalt/kühl/angenehm/warm/heiß).",
    editor_climate_overview_threshold_cold: "Kalt unter",
    editor_climate_overview_threshold_cool: "Kühl unter",
    editor_climate_overview_threshold_comfortable: "Angenehm unter",
    editor_climate_overview_threshold_warm: "Warm unter",
    editor_climate_overview_humidity_range_helper: "Komfortbereich für Luftfeuchte — außerhalb wird die Warnfarbe verwendet.",
    editor_climate_overview_humidity_min: "Feuchte min.",
    editor_climate_overview_humidity_max: "Feuchte max.",
    editor_climate_overview_scale_range_helper: "Leer lassen für automatischen Bereich aus den Messwerten.",
    editor_climate_overview_scale_min: "Skala Minimum",
    editor_climate_overview_scale_max: "Skala Maximum",
    editor_climate_overview_cold_color: "Kalt",
    editor_climate_overview_cool_color: "Kühl",
    editor_climate_overview_comfortable_color: "Angenehm",
    editor_climate_overview_warm_color: "Warm",
    editor_climate_overview_hot_color: "Heiß",
    editor_climate_overview_humidity_warn_color: "Feuchte-Warnfarbe",
    editor_climate_overview_tile_tint_opacity: "Kachel-Farbstärke",
    editor_climate_overview_accent_color: "Akzentfarbe",
    editor_climate_overview_accent_opacity: "Farbstärke",
  },
  en: {
    off: "Off",
    heat: "Heat",
    cool: "Cool",
    dry: "Dry",
    auto: "Auto",
    fan_only: "Fan only",
    heat_cool: "Heat/Cool",
    target_temperature: "Target temperature",
    unavailable: "Unavailable",
    open: "Open",
    select_preset: "Select preset",
    preset_none: "No preset",
    progress_status_running: "{remaining} min remaining",
    progress_status_running_no_remaining: "Running",
    progress_status_preparing: "Detecting load…",
    progress_status_done: "Done! Laundry is clean.",
    progress_status_ready: "Ready",
    editor_entity: "Entity",
    editor_entity_helper: "Optionally leave blank for a pure action button (e.g. to trigger an automation/script), without showing an entity state.",
    editor_content: "Content",
    editor_sensors: "Sensors",
    editor_entities: "Entities",
    editor_progress_status_entity: "Status entity",
    editor_progress_percentage_entity: "Progress (%) sensor",
    editor_progress_remaining_entity: "Remaining time (min.) sensor",
    editor_appearance: "Appearance",
    editor_behavior: "Behavior",
    editor_name: "Name",
    editor_icon: "Icon",
    editor_show_presets: "Show preset row",
    editor_show_sensors: "Show sensor chips",
    editor_temperature_sensor: "Temperature sensor",
    editor_humidity_sensor: "Humidity sensor",
    editor_window_sensor: "Window sensor",
    editor_battery_sensor: "Battery sensor",
    editor_battery_threshold: "Battery threshold",
    editor_glass_background: "Glass background",
    editor_mode_color: "Color",
    editor_preset_style: "Preset display",
    editor_preset_style_chip: "Own row (wide chip)",
    editor_preset_style_pill: "As a button in the mode row",
    editor_temperature_chip_placement: "Temperature chip position",
    editor_temp_placement_info_row: "In the sensor row",
    editor_temp_placement_header: "In the header (top right)",
    editor_hidden_modes: "Hidden modes",
    editor_height: "Card height (empty = automatic)",
    editor_interactions: "Interactions",
    editor_opacity: "Color strength",
    editor_color: "Color (on/active)",
    editor_color_helper: "Icon/background color while the entity is on/active. HA color name (e.g. red, dark-grey) or any CSS color (#hex, rgb(...))",
    editor_inactive_color: "Color (off/inactive)",
    editor_inactive_color_helper: "Icon/background color while the entity is off/inactive (also used when \"Static color\" is on). Leave blank for the theme's default grey.",
    editor_invert_colors: "Swap colors (invert on/off colors)",
    editor_static_color: "Static color (no state-based color change, uses the off/inactive color)",
    editor_unavailable_style: "Display when \"unavailable\"",
    editor_unavailable_style_dimmed: "Dimmed (default) — greyed out, not tappable",
    editor_unavailable_style_normal: "Normal — display as usual, still tappable",
    editor_unavailable_style_hidden: "Hidden — card is not shown",
    editor_radius: "Corner radius (px)",
    editor_show_state: "Show state text",
    editor_state_content: "State text content",
    editor_state_content_state: "State",
    editor_state_content_last_changed: "Last changed",
    editor_state_content_last_updated: "Last updated",
    editor_show_icon_background: "Show icon background",
    editor_icon_size: "Fixed icon size (px)",
    editor_icon_size_helper: "By default the icon size scales automatically with the tile's height (smaller tiles = smaller icon). Set a value here to make all buttons use the same fixed icon size regardless of their height. Leave blank for automatic sizing.",
    editor_align_icons: "Align icons at a fixed position",
    editor_align_icons_helper: "By default the gap between the left edge and the icon shrinks slightly on smaller tiles. Enable this so all icons sit at the same distance from the left edge regardless of tile height (e.g. for clean alignment between stacked tiles of different heights). Vertical centering is unaffected.",
    editor_vertical: "Vertical layout (icon on top)",
    editor_tap_action: "Tap action",
    editor_icon_tap_action: "Tap action (icon)",
    editor_hold_action: "Hold action",
    editor_icon_hold_action: "Hold action (icon)",
    editor_double_tap_action: "Double-tap action",
    editor_icon_double_tap_action: "Double-tap action (icon)",
    editor_show_slider: "Show slider (light/cover/fan/number)",
    editor_radius_preset: "Corner shape",
    editor_radius_square: "Square",
    editor_radius_soft: "Slightly round",
    editor_radius_round: "Round",
    editor_radius_custom: "Custom (px)",
    editor_state_colors: "State colors",
    editor_state_colors_helper: "Optional color overrides for specific states (override the \"on/active\" color above only for that state). Leave blank to use the default.",
    editor_state_on: "Color when state is \"On\"",
    editor_state_open: "Color when state is \"Open\"",
    editor_state_locked: "Color when state is \"Locked\"",
    editor_state_home: "Color when state is \"Home\"",
    editor_state_playing: "Color when state is \"Playing\"",
    editor_state_active: "Color when state is \"Active\"",
    editor_state_detected: "Color when state is \"Detected\"",
    editor_state_wet: "Color when state is \"Wet\"",
    editor_animations: "Animations",
    editor_use_corners: "Custom corners (set each corner separately)",
    editor_corner_top_left: "Top left",
    editor_corner_top_right: "Top right",
    editor_corner_bottom_right: "Bottom right",
    editor_corner_bottom_left: "Bottom left",
    editor_corners_preset: "Corner preset (fills all four corners)",
    editor_element_colors_helper: "Optional per-element color overrides, independent of the mode colors below. Leave blank to keep using the mode color (icon/power button active = current mode's color, inactive = the \"Off\" color).",
    editor_icon_active_color: "Icon color (active/on)",
    editor_icon_inactive_color: "Icon color (inactive/off)",
    editor_power_active_color: "Power button color (active/on)",
    editor_power_inactive_color: "Power button color (inactive/off)",
    editor_plus_active_color: "Plus button color (active/on)",
    editor_plus_inactive_color: "Plus button color (inactive/off)",
    editor_minus_active_color: "Minus button color (active/on)",
    editor_minus_inactive_color: "Minus button color (inactive/off)",
    editor_climate_icon_tint_opacity: "Icon background color strength",
    editor_climate_plus_tint_opacity: "Plus button background color strength",
    editor_climate_minus_tint_opacity: "Minus button background color strength",
    editor_plus_opacity: "Plus button color strength",
    editor_minus_opacity: "Minus button color strength",
    editor_progress_status_text_running: "Status text (running)",
    editor_progress_status_text_running_helper: "{remaining} is replaced with the remaining-time sensor's value.",
    editor_progress_status_text_preparing: "Status text (preparing)",
    editor_progress_status_text_done: "Status text (done)",
    editor_progress_status_text_ready: "Status text (ready)",
    editor_progress_state_mapping: "Status mapping",
    editor_progress_state_mapping_helper: "Values of the status sensor that count as \"running\" / \"preparing\" / \"done\" (case-insensitive). Comma-separated. Any other value counts as \"ready\".",
    editor_progress_running_states: "Running – status values",
    editor_progress_preparing_states: "Preparing – status values",
    editor_progress_done_states: "Done – status values",
    editor_progress_animation: "Animation",
    editor_progress_animation_auto: "Automatic (respects the system's \"reduce motion\" setting)",
    editor_progress_animation_on: "Always on",
    editor_progress_animation_off: "Off",
    editor_progress_animation_reduced_motion_hint: "Note: if the system's \"reduce motion\" setting is on, the wave won't animate regardless of this setting (accessibility).",
    editor_progress_wave_style: "Shape when animation is off",
    editor_progress_wave_style_wavy: "Wavy (frozen)",
    editor_progress_wave_style_flat: "Straight line",
    editor_progress_colors: "Colors",
    editor_progress_colors_helper: "All fields optional. Leave blank for the theme default.",
    editor_progress_accent_color: "Accent color (wave/percentage/icon)",
    editor_progress_track_color: "Track color",
    editor_progress_dot_color: "End-point color",
    editor_progress_icon_color: "Icon color",
    editor_progress_icon_background: "Icon background color",
    editor_progress_text_color: "Name color",
    editor_progress_secondary_text_color: "Status line color",
    editor_progress_card_background: "Card background",
    editor_light_transition: "Transition duration (sec.)",
    editor_light_use_light_color: "Use the entity's own light color",
    editor_light_use_light_color_helper: "When off: the accent color below is always used, even if the light supports color.",
    editor_light_accent_color: "Accent color",
    editor_light_track_color: "Track color (unfilled part)",
    editor_light_handle_color: "Handle color",
    editor_light_wave_style: "Wave style",
    editor_light_wave_style_wavy: "Wavy",
    editor_light_wave_style_flat: "Flat",
    editor_light_color_temp_style: "Color temperature control",
    editor_light_color_temp_style_presets: "Three presets",
    editor_light_color_temp_style_slider: "Continuous slider",
    editor_light_color_temp_warm: "Warm (K)",
    editor_light_color_temp_neutral: "Neutral (K)",
    editor_light_color_temp_cold: "Cold (K)",
    editor_light_show_color_wheel: "Show color wheel",
    editor_light_color_palette: "Color palette (hex, comma-separated)",
    editor_light_scenes_helper: "Each row is either a scene entity OR a custom service call.",
    editor_light_scene_entity: "Scene entity",
    editor_light_scene_service: "Service (e.g. light.turn_on)",
    editor_light_scene_service_data: "Service data (YAML)",
    editor_light_add_scene: "Add scene",
    editor_light_show_members: "List group members",
    editor_light_show_members_helper: "Only visible when the entity is a light group (has an entity_id attribute with members).",
    editor_scenes: "Scenes",
    editor_progress_state_colors: "Accent color per status",
    editor_progress_state_colors_helper: "Overrides the accent color above only for that status (e.g. green when \"done\"). Leave blank for the default.",
    editor_progress_state_running: "Accent color when \"running\"",
    editor_progress_state_preparing: "Accent color when \"preparing\"",
    editor_progress_state_done: "Accent color when \"done\"",
    editor_progress_hide_when_ready: "Hide the whole card when \"ready\"",
    editor_progress_hide_when_ready_helper: "Off by default — in the \"ready\" state only the progress bar disappears; the card stays visible with icon/name/status.",
    energy_subtitle_days: "Last {days} days",
    energy_subtitle_hours: "Today · last {hours} hours",
    energy_subtitle_months: "Per month · {months} months",
    energy_month_suffix: "in {month}",
    energy_month_no_statistics: "No monthly statistics were found for this entity. Check under Developer Tools → Statistics.",
    energy_month_chip_less: "{value}% below {month}",
    energy_month_chip_more: "{value}% above {month}",
    energy_month_chip_average: "Avg {value} {unit}",
    energy_today_suffix: "today",
    energy_hour_suffix: "this hr.",
    energy_weekday_today: "Today",
    energy_hour_now: "Now",
    energy_subtitle_solar: "Today · daily trend",
    energy_solar_default_name: "Solar production",
    energy_solar_expected: "from {value} {unit} expected",
    energy_solar_chip_more: "{value} % more than yesterday",
    energy_solar_chip_less: "{value} % less than yesterday",
    energy_legend_generated: "Generated",
    energy_legend_forecast: "Forecast",
    gauge_subtitle_today: "Today",
    gauge_no_data: "No data today",
    gauge_no_energy_dashboard: "No Energy dashboard configured",
    gauge_net_grid: "Net drawn from grid",
    gauge_net_feed_in: "Net fed into grid",
    gauge_label_a: "Grid draw",
    gauge_label_b: "Feed-in",
    counter_subtitle_default: "Total reading",
    counter_ticker_today: "today",
    editor_energy_mode: "Card type",
    editor_energy_mode_consumption: "Consumption/generation (bars per day/hour)",
    editor_energy_mode_solar: "Solar daily trend with forecast",
    editor_energy_source: "Data source",
    editor_energy_source_energy: "Energy dashboard (all solar sources, default)",
    editor_energy_source_entity: "Custom sensor",
    editor_energy_entity: "Energy sensor",
    editor_energy_statistic_type: "Statistic type",
    editor_energy_statistic_type_state: "End-of-day value (resets daily) — default",
    editor_energy_statistic_type_change: "Change (never-resetting total counter)",
    editor_energy_days: "Number of days",
    editor_energy_period: "Period",
    editor_energy_period_day: "Days",
    editor_energy_period_hour: "Hours",
    editor_energy_period_month: "Months",
    editor_energy_hours: "Number of hours",
    editor_energy_months: "Number of months",
    editor_energy_forecast_entity: "Custom forecast sensor (optional)",
    editor_energy_full_day: "Always show 0-24h (instead of trimming to generation/forecast)",
    editor_energy_show_values: "Show values above bars",
    editor_energy_show_legend: "Show legend (Generated/Forecast)",
    editor_energy_show_projection: "Show projection for the current month",
    editor_energy_show_average: "Show average line",
    editor_energy_show_comparison: "Show comparison chips",
    editor_energy_higher_is_better: "Higher is better (e.g. generation instead of consumption)",
    editor_energy_comparison_better_color: "\"Better\" color (comparison chip)",
    editor_energy_comparison_worse_color: "\"Worse\" color (comparison chip)",
    editor_energy_comparison_tint_opacity: "Color strength (comparison chip)",
    editor_energy_subtitle: "Subtitle (empty = automatic)",
    editor_energy_unit: "Unit (overrides the entity's own, e.g. \"L\")",
    editor_energy_accent_color: "Accent color (today's bar)",
    editor_energy_bar_tint_color: "Past-day bar color (empty = derived from accent)",
    editor_energy_fallback_hint: "No long-term statistics were found for this entity — falling back to the History API (less accurate, aggregates daily values by maximum). Check under Developer Tools → Statistics.",
    editor_gauge_source: "Data source",
    editor_gauge_source_energy: "Energy dashboard (default)",
    editor_gauge_source_entities: "Two custom sensors",
    editor_gauge_value_a_entity: "Sensor A (draw)",
    editor_gauge_value_b_entity: "Sensor B (feed-in)",
    editor_gauge_label_positive: "Text for positive net (draw)",
    editor_gauge_label_negative: "Text for negative net (feed-in)",
    editor_gauge_label_a: "Legend label A",
    editor_gauge_label_b: "Legend label B",
    editor_gauge_segment_a_color: "Segment A color",
    editor_gauge_segment_b_color: "Segment B color",
    editor_gauge_track_color: "Track color (no data)",
    editor_counter_power_entity: "Power sensor (header chip)",
    editor_counter_daily_entity: "Daily sensor (for ticker line)",
    editor_counter_decimals: "Decimal places",
    editor_counter_digits_mode: "Integer digits",
    editor_counter_digits_auto: "Automatic (grows with the value, min. 5)",
    editor_counter_digits_fixed: "Fixed count",
    editor_counter_digits: "Number of integer digits",
    editor_counter_show_ticker: "Show ticker line (\"+X today\")",
    editor_counter_accent_color: "Accent color (decimal places)",
    editor_counter_cell_background: "Cell background (integer places)",
    editor_counter_power_chip_color: "Power chip color (default)",
    editor_counter_power_thresholds: "Color change above threshold (format: \"2000:orange, 3500:red\")",
    editor_counter_calibration: "Calibration",
    editor_counter_calibration_hint: "Sets the counter to a new value once, e.g. to align it with an analog meter. Statistics history is left untouched.",
    editor_counter_calibration_current: "Current value",
    editor_counter_calibration_new_value: "New value",
    editor_counter_calibration_button: "Calibrate now",
    editor_counter_calibration_success: "Calibrated.",
    editor_counter_calibration_error: "Calibration failed.",
    power_list_default_name: "Sockets",
    power_list_subtitle: "{active} of {total} active",
    power_list_total_suffix: "W total",
    power_list_empty: "Nothing is drawing power right now",
    power_list_show_idle: "show idle devices",
    power_list_hide_idle: "hide idle devices",
    editor_power_list_entities: "Sensors",
    editor_power_list_entities_helper: "Power sensors (W) in display order. For per-entry name/icon/type overrides, fine-tune directly in the card's YAML editor.",
    editor_power_list_auto_discover: "Auto-discover (all sensors with device_class \"power\")",
    editor_power_list_include_area: "Only these areas (empty = all)",
    editor_power_list_include_label: "Only these labels (empty = all)",
    editor_power_list_exclude_entities: "Excluded sensors",
    editor_power_list_threshold: "\"Active\" threshold (W)",
    editor_power_list_sort: "Sort order",
    editor_power_list_sort_power_desc: "Power descending (default)",
    editor_power_list_sort_power_asc: "Power ascending",
    editor_power_list_sort_name: "Name",
    editor_power_list_sort_config: "Order as configured",
    editor_power_list_max_visible: "Max. visible rows (0 = all active)",
    editor_power_list_show_idle_toggle: "Show expand area for idle devices",
    editor_power_list_subtitle: "Subtitle (empty = automatic)",
    editor_power_list_accent_color: "Accent color (consumers)",
    editor_power_list_producer_color: "Producer color",
    editor_power_list_bar_tint_color: "Share bar color (empty = automatic from accent)",
    power_summary_export: "Feeding into the grid",
    power_summary_import: "Drawing from the grid",
    power_summary_neutral: "Balanced",
    power_summary_unavailable: "Unavailable",
    power_summary_self_use: "Self-consumption",
    power_summary_grid_share: "Grid share",
    power_summary_surplus: "Surplus",
    editor_summary_grid_entity: "Grid sensor (W)",
    editor_summary_grid_sign: "Sign convention",
    editor_summary_grid_sign_negative: "Negative = export (default)",
    editor_summary_grid_sign_positive: "Positive = export",
    editor_summary_consumption_entity: "Consumption sensor (W, optional)",
    editor_summary_solar_entity: "Solar sensor(s) (W, optional)",
    editor_summary_label_export: "Label when exporting",
    editor_summary_label_import: "Label when importing",
    editor_summary_show_self_sufficiency: "Show self-sufficiency chip",
    editor_summary_show_split_bar: "Show share bar",
    editor_summary_zero_threshold: "\"Balanced\" threshold (W)",
    editor_summary_kw_threshold: "Threshold for kW display (W)",
    editor_summary_metrics: "Metric fields",
    editor_summary_metrics_helper: "One line per field: entity | name (optional) | icon (optional) | type (consumer/producer, optional)",
    editor_summary_export_color: "\"Export\" color",
    editor_summary_import_color: "\"Import\" color",
    editor_summary_producer_color: "Producer color",
    editor_summary_flow_tint_opacity: "Flow color strength",
    editor_summary_accent_color: "Accent color (self-sufficiency chip)",
    top_consumers_default_name: "Top consumers",
    top_consumers_period_today: "Today",
    top_consumers_period_yesterday: "Yesterday",
    top_consumers_period_week: "Last 7 days",
    top_consumers_period_month: "This month",
    top_consumers_device_count: "{n} devices",
    top_consumers_total_suffix: "kWh total",
    top_consumers_of_total: "of total consumption",
    top_consumers_more_devices: "{n} more devices",
    top_consumers_empty: "No consumption data yet for {period}",
    top_consumers_no_device_section: "This Energy dashboard has no individual devices section configured.",
    top_consumers_open_energy_settings: "Open Energy dashboard",
    editor_top_consumers_source_header: "Data source",
    editor_top_consumers_source: "Source",
    editor_top_consumers_source_energy: "Energy dashboard (devices section, default)",
    editor_top_consumers_source_entities: "Custom sensor list",
    editor_top_consumers_entities: "Energy sensors (kWh)",
    editor_top_consumers_period: "Period",
    editor_top_consumers_period_today: "Today",
    editor_top_consumers_period_yesterday: "Yesterday",
    editor_top_consumers_period_week: "Last 7 days",
    editor_top_consumers_period_month: "This month",
    editor_top_consumers_top_count: "Number of full rows",
    editor_top_consumers_rest_mode: "Rest behavior",
    editor_top_consumers_rest_collapse: "Collapsible summary row (default)",
    editor_top_consumers_rest_hide: "Hide",
    editor_top_consumers_rest_show_all: "Show all as full rows",
    editor_top_consumers_name_strip_header: "Name cleanup",
    editor_top_consumers_name_strip_helper: "Regex/text patterns removed from entity names (e.g. \"^Steckdose \\d+ - \"). Overridable per entity via its own name.",
    editor_top_consumers_name_strip: "Patterns",
    editor_top_consumers_accent_color: "Accent color (total)",
    editor_top_consumers_palette: "Device color palette (assigned cyclically)",
    cost_default_name: "Cost",
    cost_no_price_configured: "No price configured.",
    cost_subtitle_day: "Cost today",
    cost_subtitle_day_date: "Cost on {date}",
    cost_nav_period_label: "Period",
    cost_subtitle_month: "Cost in {month}",
    cost_subtitle_year: "Cost {year}",
    cost_credit_label: "Credit",
    cost_forecast_hint: "Forecast from tomorrow",
    cost_chip_more: "{value} % more than previous period",
    cost_chip_less: "{value} % less than previous period",
    cost_budget_percent: "{value} % of budget",
    cost_avg_per_day: "Avg {value} / day",
    cost_tariff_label: "Unit price",
    editor_cost_price_section: "Price",
    editor_cost_price_source: "Price source",
    editor_cost_price_source_energy_dashboard: "Energy dashboard (default)",
    editor_cost_price_source_input_number: "input_number helper",
    editor_cost_price_source_fixed: "Fixed price",
    editor_cost_price_entity: "Price helper (input_number)",
    editor_cost_price: "Price per kWh",
    editor_cost_price_unit: "Price unit",
    editor_cost_price_unit_eur: "currency/kWh",
    editor_cost_price_unit_ct: "cents/kWh",
    editor_cost_price_unit_custom: "Custom",
    editor_cost_price_unit_label: "Unit (display, e.g. €/m³)",
    editor_cost_price_quantity_factor: "Quantity conversion factor",
    editor_cost_base_fee: "Base fee (currency/month)",
    editor_cost_base_fee_helper: "Added pro-rated per day to the total when period is \"month\".",
    editor_cost_currency: "Currency (ISO code, e.g. EUR)",
    editor_cost_period: "Period",
    editor_cost_period_day: "Today",
    editor_cost_period_month: "Month",
    editor_cost_period_year: "Year",
    editor_cost_entity: "Energy sensor (kWh)",
    editor_cost_show_projection: "Show forecast chip",
    editor_cost_show_comparison: "Show comparison chip",
    editor_cost_budget: "Budget (optional)",
    editor_top_consumers_unit_mode: "Display",
    editor_top_consumers_unit_mode_energy: "Energy (kWh)",
    editor_top_consumers_unit_mode_cost: "Cost",
    top_consumers_of_total_cost: "of cost",
    light_default_name: "Light",
    light_brightness_label: "Brightness",
    light_color_temp_label: "Color temperature",
    light_color_wheel_label: "Color",
    light_scene_unnamed: "Scene",
    battery_default_name: "Batteries",
    battery_subtitle_attention: "{n} need attention",
    battery_subtitle_ok: "All good",
    battery_empty: "No battery entities found. The card auto-discovers sensors with device_class \"battery\" (auto_discover), or add them manually under \"entities\".",
    battery_value_unavailable: "—",
    battery_expand: "Show {n} more",
    battery_collapse: "Collapse",
    editor_battery_auto_discover: "Auto-discover",
    editor_battery_auto_discover_helper: "Automatically finds all sensors with device_class \"battery\". Entries below then only override name/icon of individual devices instead of replacing the list.",
    editor_battery_convert_to_manual: "Take over current list & manage manually",
    editor_battery_convert_to_manual_helper: "Copies all {n} currently auto-discovered devices into a fixed list — then remove the ones you don't want with \"×\" instead of re-adding every device you want to keep.",
    editor_battery_include_area: "Restrict to area",
    editor_battery_include_label: "Restrict to label",
    editor_battery_exclude_entities: "Excluded entities",
    editor_battery_overrides_helper: "Without \"Auto-discover\" this is the full device list. With \"Auto-discover\" an entry only overrides that device's name/icon.",
    editor_battery_override_entity: "Entity",
    editor_battery_add_override: "Add device",
    editor_battery_thresholds: "Thresholds",
    editor_battery_thresholds_helper: "Charge level in % below which the respective stage applies.",
    editor_battery_threshold_critical: "Critical below",
    editor_battery_threshold_low: "Low below",
    editor_battery_threshold_medium: "Medium below",
    editor_battery_name_strip: "Strip name suffixes",
    editor_battery_max_visible: "Max. visible devices (0 = all)",
    editor_battery_show_healthy_toggle: "Show expand button for remaining devices",
    editor_battery_critical_color: "\"Critical\" color",
    editor_battery_low_color: "\"Low\" color",
    editor_battery_medium_color: "\"Medium\" color",
    editor_battery_ok_color: "\"OK\" color",
    editor_battery_unavailable_color: "\"Unavailable\" color",
    editor_battery_stage_tint_opacity: "Status color strength",
    a11y_more_info: "More info about {name}",
    a11y_toggle_expand: "Show more",
    a11y_toggle_collapse: "Collapse",
    flow_default_name: "Energy flow",
    flow_subtitle_today: "Today",
    flow_node_pv: "Solar",
    flow_node_grid: "Grid",
    flow_node_home: "Home",
    flow_node_battery: "Battery",
    flow_self_sufficiency: "Self-sufficiency today",
    editor_flow_source: "Data source",
    editor_flow_source_energy: "Energy dashboard (default)",
    editor_flow_source_entities: "Custom sensors",
    editor_flow_solar_entity: "Solar sensor (today, kWh)",
    editor_flow_grid_import_entity: "Grid import sensor (today, kWh)",
    editor_flow_grid_export_entity: "Grid export sensor (today, kWh)",
    editor_flow_battery_entity: "Battery discharge sensor (today, kWh, optional)",
    editor_flow_show_self_sufficiency: "Show self-sufficiency indicator",
    editor_flow_pv_color: "Solar color",
    editor_flow_grid_color: "Grid color",
    editor_flow_home_color: "Home color",
    editor_flow_self_sufficiency_color: "Self-sufficiency color",
    editor_flow_node_tint_opacity: "Node color strength",
    editor_flow_speed: "Flow speed",
    editor_flow_speed_slow: "Slow",
    editor_flow_speed_normal: "Normal",
    editor_flow_speed_fast: "Fast",
    weather_now: "Now",
    weather_today: "Today",
    weather_no_hourly_forecast: "This weather entity doesn't provide an hourly forecast.",
    weather_last_known: "Last known reading",
    weather_days_expand: "Show {n} more",
    weather_days_collapse: "Collapse",
    editor_weather_hours: "Number of hours",
    editor_weather_days: "Number of days",
    editor_weather_days_helper:
      "0 = hide the daily forecast. How many days actually show up depends on the weather integration (Met.no delivers 6 days max) — from 4 days on, the list is collapsible by default.",
    editor_weather_show_days_toggle: "Show expand button for additional days",
    editor_weather_no_entity_hint:
      "No weather entity found. If you don't have your own weather station, Home Assistant's built-in, free Met.no integration works without an API key: Settings → Devices & Services → Add Integration → search for \"Met.no\". It automatically uses your Home zone's coordinates.",
    editor_weather_chip_no_data: "no data",
    editor_weather_chips_helper:
      "Not every weather integration provides every value — Met.no, for example, has no \"feels like\" or visibility data. Chips without data stay hidden even when selected.",
    editor_weather_chips: "Chips",
    editor_weather_show_sun: "Show sunrise/sunset",
    editor_weather_accent_color: "Temperature curve",
    editor_weather_precipitation_color: "Precipitation",
    editor_weather_gradient_color: "Gradient fill",
    chip_apparent_temperature: "Feels like",
    chip_wind_speed: "Wind",
    chip_humidity: "Humidity",
    chip_pressure: "Pressure",
    chip_uv_index: "UV index",
    chip_visibility: "Visibility",
    presence_default_name: "Home",
    presence_subtitle: "{home} of {total} home",
    presence_nobody_home: "Nobody home",
    presence_empty: "No people configured.",
    presence_home: "Home",
    presence_not_home: "Away",
    since_minutes: "for {n} min",
    since_hours: "for {n} h",
    since_days: "for {n} d",
    editor_presence_auto_discover: "Auto-discover all person entities",
    editor_presence_show_distance: "Show distance",
    editor_presence_show_since: "Show time away",
    editor_presence_show_map: "Show map preview",
    editor_presence_show_map_helper: "Embeds Home Assistant's own map card — can noticeably increase resource usage with many people/updates.",
    editor_presence_sort: "Sorting",
    editor_presence_sort_home_first: "Home first",
    editor_presence_sort_name: "Alphabetical",
    editor_presence_home_color: "Home",
    editor_presence_not_home_color: "Away",
    editor_presence_zone_color: "Zone (default)",
    editor_presence_unknown_color: "Unknown",
    media_off: "Off",
    media_idle: "Ready",
    media_volume_label: "Volume",
    editor_media_show_source_select: "Show source selection",
    editor_media_show_shuffle_repeat: "Show shuffle/repeat",
    editor_media_use_artwork_color: "Accent color from artwork",
    editor_media_accent_color: "Accent color (fallback)",
    climate_overview_default_name: "Climate",
    climate_overview_subtitle: "{n} rooms · avg {temp}",
    climate_overview_subtitle_one: "1 room · avg {temp}",
    climate_overview_empty: "No temperature sensors found.",
    climate_overview_unavailable: "—",
    climate_overview_compare: "Comparison",
    climate_overview_mold_risk: "Mold risk",
    aquarium_default_name: "Aquarium",
    aquarium_water_label: "Water",
    aquarium_state_on: "On",
    aquarium_action_start: "Start",
    aquarium_cleaned_today: "Today",
    aquarium_cleaned_days_ago: "{n}d ago",
    aquarium_phase_day: "Day phase",
    aquarium_phase_night: "Night rest",
    aquarium_phase_light_from: "Light from {time}",
    aquarium_phase_remaining_hours: "{h}h left",
    aquarium_phase_remaining_minutes: "{m}m left",
    aquarium_live: "LIVE",
    aquarium_camera_no_image: "No image",
    aquarium_camera_toggle: "Toggle camera image",
    aquarium_chip_temp_above: "{x}K above target",
    aquarium_chip_temp_below: "{x}K below target",
    aquarium_chip_heater_no_power: "Heater on · 0 W",
    aquarium_chip_cleaning_due: "Cleaning due",
    aquarium_chip_cleaned_days_ago: "Cleaned {n}d ago",
    aquarium_chip_cleaned_today: "Cleaned today",
    aquarium_chip_water_level_low: "Water level low",
    editor_aquarium_general: "General",
    editor_aquarium_accent_color: "Accent color",
    editor_aquarium_tile_tint_opacity: "Tile color strength",
    editor_aquarium_water: "Water values",
    editor_aquarium_water_temperature_entity: "Water temperature sensor",
    editor_aquarium_target_min: "Target range min",
    editor_aquarium_target_max: "Target range max",
    editor_aquarium_ph_entity: "pH sensor",
    editor_aquarium_tds_entity: "TDS sensor",
    editor_aquarium_water_level_entity: "Water level sensor (problem flag, binary_sensor)",
    editor_aquarium_power_entity: "Total power sensor",
    editor_aquarium_devices: "Devices",
    editor_aquarium_light_day: "Day light",
    editor_aquarium_light_night: "Night light",
    editor_aquarium_pump: "Pump",
    editor_aquarium_heater: "Heater",
    editor_aquarium_heater_power_entity: "Heater power sensor",
    editor_aquarium_co2: "CO₂",
    editor_aquarium_extra_devices: "Extra devices",
    editor_aquarium_add_device: "Add device",
    editor_aquarium_camera: "Camera",
    editor_aquarium_camera_entity: "Camera entity",
    editor_aquarium_camera_style: "Style",
    editor_aquarium_camera_style_none: "None",
    editor_aquarium_camera_style_thumbnail: "Thumbnail",
    editor_aquarium_camera_style_banner: "Banner",
    editor_aquarium_camera_style_live: "Live stream",
    editor_aquarium_camera_refresh: "Image refresh (sec., 0 = off)",
    editor_aquarium_camera_live_on_tap: "Tap opens live stream",
    editor_aquarium_schedule: "Lighting schedule",
    editor_aquarium_schedule_entity: "Schedule helper (schedule domain)",
    editor_aquarium_schedule_helper: "A schedule helper overrides the manual phase list below if both are set.",
    editor_aquarium_show_schedule: "Show day arc",
    editor_aquarium_phase_device: "Phase",
    editor_aquarium_phase_day: "Day",
    editor_aquarium_phase_night: "Night",
    editor_aquarium_phase_start: "Start",
    editor_aquarium_phase_end: "End",
    editor_aquarium_add_phase: "Add phase",
    editor_aquarium_maintenance: "Maintenance",
    editor_aquarium_cleaning_entity: "Cleaning timestamp (input_datetime)",
    editor_aquarium_cleaning_interval: "Cleaning interval (days)",
    editor_climate_overview_auto_discover: "Auto-discover",
    editor_climate_overview_auto_discover_helper: "Automatically finds all sensors with device_class \"temperature\" or \"humidity\", grouped by area/device.",
    editor_climate_overview_include_area: "Restrict to area",
    editor_climate_overview_exclude_entities: "Excluded entities",
    editor_climate_overview_rooms_helper: "Manual room list (overrides auto-discovery when not empty).",
    editor_climate_overview_add_room: "Add room",
    editor_climate_overview_room_name: "Name",
    editor_climate_overview_room_icon: "Icon",
    editor_climate_overview_room_temp_entity: "Temperature sensor",
    editor_climate_overview_room_humidity_entity: "Humidity sensor",
    editor_climate_overview_room_color: "Custom color (overrides temperature color)",
    editor_climate_overview_sort: "Sorting",
    editor_climate_overview_sort_area: "Area (default)",
    editor_climate_overview_sort_temp_desc: "Temperature descending",
    editor_climate_overview_sort_temp_asc: "Temperature ascending",
    editor_climate_overview_sort_name: "Alphabetical",
    editor_climate_overview_show_scale: "Show comparison scale",
    editor_climate_overview_show_outlier_chip: "Show outlier chip",
    editor_climate_overview_show_trend: "Show trend arrow",
    editor_climate_overview_show_mold_warning: "Show mold warning",
    editor_climate_overview_name_strip: "Strip name suffixes",
    editor_climate_overview_thresholds_helper: "Boundaries between the temperature color stages (cold/cool/comfortable/warm/hot).",
    editor_climate_overview_threshold_cold: "Cold below",
    editor_climate_overview_threshold_cool: "Cool below",
    editor_climate_overview_threshold_comfortable: "Comfortable below",
    editor_climate_overview_threshold_warm: "Warm below",
    editor_climate_overview_humidity_range_helper: "Comfort range for humidity — the warning color is used outside it.",
    editor_climate_overview_humidity_min: "Humidity min",
    editor_climate_overview_humidity_max: "Humidity max",
    editor_climate_overview_scale_range_helper: "Leave blank for an automatic range from the measured values.",
    editor_climate_overview_scale_min: "Scale minimum",
    editor_climate_overview_scale_max: "Scale maximum",
    editor_climate_overview_cold_color: "Cold",
    editor_climate_overview_cool_color: "Cool",
    editor_climate_overview_comfortable_color: "Comfortable",
    editor_climate_overview_warm_color: "Warm",
    editor_climate_overview_hot_color: "Hot",
    editor_climate_overview_humidity_warn_color: "Humidity warning color",
    editor_climate_overview_tile_tint_opacity: "Tile color strength",
    editor_climate_overview_accent_color: "Accent color",
    editor_climate_overview_accent_opacity: "Color strength",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["en"];

function resolveLang(language?: string): Lang {
  return language?.toLowerCase().startsWith("de") ? "de" : "en";
}

export function localize(key: TranslationKey, language?: string): string {
  const lang = resolveLang(language);
  return translations[lang][key] ?? translations.en[key] ?? key;
}
